[package]
name = "advent_of_code_2019"
version = "0.1.0"
authors = ["Baspar <me@bastien-laine.io>"]
edition = "2018"

[dependencies]
regex = "1"
num = "0.2"
itertools = "0.8.2"
text_io = "0.1.7"
ndarray = "0.13.0"
onig = "4.3"
